name: CY_Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
#    Use environment if the secrets is inside a github environment. You will need to specify the environment like the example below:
    environment: cypress_environment

    steps:     
      # Checkout git repo
       - uses: actions/checkout@v2

       - name: Install dependencies
         run: npm install

      # Run Cypress tests
       - name: 'Run Cypress tests'
  
  #    If the github secrets is inside a repository secrets then you can call it like normally without specifying an environment. 
         env:
            CYPRESS_auth_username: ${{ secrets.AUTH_USERNAME }}
            CYPRESS_auth_password: ${{ secrets.AUTH_PASSWORD }}

         run: npm run test