name: CY_Pipeline

on:
  
  push:
    branches:
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest
    environment: cypress_auth
    steps:     
      # Checkout git repo
       - uses: actions/checkout@v2

       - name: Install dependencies
         run: npm install

      # Run Cypress tests
       - name: 'Run Cypress tests'
  
         env:
            CYPRESS_auth_username: ${{ secrets.AUTH_USERNAME }}
            CYPRESS_auth_password: ${{ secrets.AUTH_PASSWORD }}

         run: npm run test