name: CY_Pipeline

on:
  
  push:
    branches:
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:     
      # Checkout git repo
       - uses: actions/checkout@v2

       - name: Install dependencies
         run: npm install

      # Run Cypress tests
       - name: 'Run Cypress tests'
         env:
            CYPRESS_auth_username: ${{ secrets.cypress_env.AUTH_USERNAME }}
#            CYPRESS_auth_username: 'testuser'
#            AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
#            AUTH_USERNAME: 'Testadmin@gmail.com'
#            AUTH_PASSWORD: 'TestAuth0Admin1234'
         run: npm run test